Repository OpenNebula/website, pull requests merged in 2025-09, with the labels that each got.

#276 F OpenNebula/one#7219: remove abstracts from Solutions parent pages
  content/solutions/certified_hw_platforms/ampere_opennebula/_index.md
  content/solutions/hosted_cloud_providers/ionos_opennebula/_index.md
Labels: documentation

#286 B OpenNebula/one#7231: Avoid Host not permitted on Sinatra server when is behind NGINX proxy
  content/software/release_information/release_notes_enterprise/resolved_issues_701.md
Labels: bug, documentation

#298 add platform notes for SAN storage
  content/software/release_information/release_notes_70/platform_notes.md
Labels: enhancement

#300 F OpenNebula/one#7243: Updated sidebar titles and added Overview
  content/software/installation_process/automatic_installation_with_onedeploy/one_deploy_tutorial_local_ds.md
  content/software/installation_process/automatic_installation_with_onedeploy/one_deploy_tutorial_shared_ds.md
  content/software/installation_process/build_from_source_code/compile.md
  content/software/installation_process/manual_installation/_index.md
  content/software/installation_process/manual_installation/database.md
  content/software/installation_process/manual_installation/front_end_installation.md
  content/software/installation_process/manual_installation/kvm_node_installation.md
  content/software/installation_process/manual_installation/lxc_node_installation.md
  content/software/installation_process/manual_installation/opennebula_repository_configuration.md
  content/software/migration_from_vmware/import_ova.md
  content/software/migration_from_vmware/oneswap.md
  content/software/migration_from_vmware/overview.md
  content/software/release_information/release_notes_community/what_is.md
  content/software/release_information/release_notes_enterprise/what_is.md
  content/software/upgrade_process/configuration_management_ee/appendix.md
  content/software/upgrade_process/upgrade_guide/upgrading_federation.md
  content/software/upgrade_process/upgrade_guide/upgrading_ha.md
  content/software/upgrade_process/upgrade_guide/upgrading_single.md
Labels: documentation
